add test trigger and check before publishing orb

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,6 +32,31 @@ jobs:
       - run: 
           name: Test by Publishing a Dev Version
           command: circleci orb publish << pipeline.parameters.orb-file >> << pipeline.parameters.orb-name >>@dev:<< pipeline.git.revision >>
+      - run:
+          name: Trigger a test deployment with the dev version
+          command: |
+              curl -X POST https://circleci.com/api/v2/project/github/vjpandian/mac-runner-cache-test/pipeline \
+              --header "Circle-Token: $CIRCLE_TOKEN" \
+              --header "content-type: application/json" \
+              --data '{"branch":"orb-dev-version-test"}'
+      - run: 
+          name: Check if the triggered test deployment was successful
+          command: |
+             # Make a request to the CircleCI API to get the latest pipeline for the specified branch
+             pipeline_status=$(curl -s -u "${CIRCLECI_TOKEN}:" "https://circleci.com/api/v2/project/github/vjpandian/mac-runner-cache-test/pipeline?branch=orb-dev-version-test" | jq -r '.items[0].state')
+             sleep 5
+             # Check the pipeline status and act accordingly
+             if [ "$pipeline_status" = "success" ]; then
+               echo "Pipeline is successful"
+               exit 0
+             elif [ "$pipeline_status" = "failed" ]; then
+               echo "Pipeline has failed"
+               exit 1
+             else
+               echo "Pipeline is in an unknown state: $pipeline_status"
+               exit 2
+             fi
+
       - run: 
           name: Promote the published Dev Version
           command: circleci orb publish promote << pipeline.parameters.orb-name >>@dev:<< pipeline.git.revision >> patch
